//TEMPORARY DATA
//THE DATA COMES DIRECTLY FROM INSIDE THE CURRENT MODULE

const posts = [
    {
        id: 1,
        Username: "Canada Goose",
        Gender: "Male",
        School: "Maple Leaf Elementary School",
        Grade: "6th grade",
        Subjects: "Mathematics",
        Language: "English",
        Schedule: "Mon-Fri, 8:00 AM - 12:00 PM",
        Timezone: "UTC -5",
        Salary: "50 CAD",
        Date: "2024.02.18",
        userId: 1
    },
    {
        id: 2,
        Username: "Iron Man",
        Gender: "Male",
        School: "Liberty Middle School",
        Grade: "8th grade",
        Subjects: "Science",
        Language: "Spanish",
        Schedule: "Mon-Fri, 1:00 PM - 5:00 PM",
        Timezone: "UTC -5",
        Salary: "55 CAD",
        Date: "2024.02.18",
        userId: 2
    },
    {
        id: 3,
        Username: "Superman",
        Gender: "Male",
        School: "Golden High School",
        Grade: "10th grade",
        Subjects: "Physics",
        Language: "English",
        Schedule: "Mon-Fri, 9:00 AM - 3:00 PM",
        Timezone: "UTC -8",
        Salary: "60 CAD",
        Date: "2024.02.18",
        userId: 3
    },
    {
        id: 4,
        Username: "Wonder Woman",
        Gender: "Female",
        School: "Starlight Academy",
        Grade: "12th grade",
        Subjects: "Literature",
        Language: "French",
        Schedule: "Mon-Thu, 10:00 AM - 2:00 PM",
        Timezone: "UTC -5",
        Salary: "65 CAD",
        Date: "2024.02.18",
        userId: 4
    },
    {
        id: 5,
        Username: "Batman",
        Gender: "Male",
        School: "Gotham City High School",
        Grade: "Senior",
        Subjects: "Chemistry",
        Language: "English",
        Schedule: "Tue-Sat, 2:00 PM - 6:00 PM",
        Timezone: "UTC -5",
        Salary: "70 CAD",
        Date: "2024.02.18",
        userId: 5
    },
    {
        id: 6,
        Username: "Spider-Man",
        Gender: "Male",
        School: "Midtown School of Science and Technology",
        Grade: "Junior",
        Subjects: "Biology",
        Language: "English",
        Schedule: "Mon-Fri, 8:00 AM - 12:00 PM",
        Timezone: "UTC -5",
        Salary: "60 CAD",
        Date: "2024.02.18",
        userId: 6
    },
    {
        id: 7,
        Username: "Captain America",
        Gender: "Male",
        School: "Brooklyn High School",
        Grade: "Freshman",
        Subjects: "History",
        Language: "English",
        Schedule: "Mon-Thu, 9:00 AM - 3:00 PM",
        Timezone: "UTC -5",
        Salary: "55 CAD",
        Date: "2024.02.18",
        userId: 7
    },
    {
        id: 8,
        Username: "Black Widow",
        Gender: "Female",
        School: "Red Room Academy",
        Grade: "Junior",
        Subjects: "Political Science",
        Language: "Russian",
        Schedule: "Tue-Fri, 11:00 AM - 3:00 PM",
        Timezone: "UTC -5",
        Salary: "70 CAD",
        Date: "2024.02.18",
        userId: 8
    },
    {
        id: 9,
        Username: "Hulk",
        Gender: "Male",
        School: "Baxter High School",
        Grade: "Senior",
        Subjects: "Environmental Science",
        Language: "English",
        Schedule: "Mon-Wed, 10:00 AM - 2:00 PM",
        Timezone: "UTC -8",
        Salary: "65 CAD",
        Date: "2024.02.18",
        userId: 9
    },
    {
        id: 10,
        Username: "Thor",
        Gender: "Male",
        School: "Asgardian School of Magic",
        Grade: "Senior",
        Subjects: "Astronomy",
        Language: "Old Norse",
        Schedule: "Mon-Thu, 8:00 AM - 12:00 PM",
        Timezone: "UTC -8",
        Salary: "75 CAD",
        Date: "2024.02.18",
        userId: 10
    },
    {
        id: 11,
        Username: "Flash",
        Gender: "Male",
        School: "Central City High School",
        Grade: "Junior",
        Subjects: "Psychology",
        Language: "English",
        Schedule: "Tue-Fri, 9:00 AM - 3:00 PM",
        Timezone: "UTC -6",
        Salary: "60 CAD",
        Date: "2024.02.18",
        userId: 11
    },
    {
        id: 12,
        Username: "Green Lantern",
        Gender: "Male",
        School: "Oa Institute",
        Grade: "Freshman",
        Subjects: "Engineering",
        Language: "English",
        Schedule: "Mon-Thu, 10:00 AM - 2:00 PM",
        Timezone: "UTC -5",
        Salary: "55 CAD",
        Date: "2024.02.18",
        userId: 12
    },
    {
        id: 13,
        Username: "Aquaman",
        Gender: "Male",
        School: "Atlantis Academy",
        Grade: "Senior",
        Subjects: "Oceanography",
        Language: "Atlantean",
        Schedule: "Tue-Fri, 11:00 AM - 3:00 PM",
        Timezone: "UTC -6",
        Salary: "70 CAD",
        Date: "2024.02.18",
        userId: 13
    },
    {
        id: 14,
        Username: "Wolverine",
        Gender: "Male",
        School: "Xavier's School for Gifted Youngsters",
        Grade: "Graduate",
        Subjects: "Medicine",
        Language: "English",
        Schedule: "Mon-Thu, 9:00 AM - 3:00 PM",
        Timezone: "UTC -5",
        Salary: "65 CAD",
        Date: "2024.02.18",
        userId: 14
    },
    {
        id: 15,
        Username: "Black Panther",
        Gender: "Male",
        School: "Wakanda International School",
        Grade: "Senior",
        Subjects: "Geology",
        Language: "Wakandan",
        Schedule: "Mon-Wed, 8:00 AM - 12:00 PM",
        Timezone: "UTC -6",
        Salary: "75 CAD",
        Date: "2024.02.18",
        userId: 15
    },
    {
        id: 16,
        Username: "Storm",
        Gender: "Female",
        School: "Ororo Munroe School for Gifted Youngsters",
        Grade: "Sophomore",
        Subjects: "Meteorology",
        Language: "Swahili",
        Schedule: "Tue-Fri, 10:00 AM - 2:00 PM",
        Timezone: "UTC -8",
        Salary: "60 CAD",
        Date: "2024.02.18",
        userId: 16
    },
    {
        id: 17,
        Username: "Doctor Strange",
        Gender: "Male",
        School: "Kamar-Taj Academy",
        Grade: "Freshman",
        Subjects: "Philosophy",
        Language: "English",
        Schedule: "Mon-Thu, 11:00 AM - 3:00 PM",
        Timezone: "UTC -5",
        Salary: "55 CAD",
        Date: "2024.02.18",
        userId: 17
    },
    {
        id: 18,
        Username: "Ant-Man",
        Gender: "Male",
        School: "Pym Technologies Institute",
        Grade: "Junior",
        Subjects: "Entomology",
        Language: "English",
        Schedule: "Mon-Wed, 9:00 AM - 3:00 PM",
        Timezone: "UTC -8",
        Salary: "70 CAD",
        Date: "2024.02.18",
        userId: 18
    },
    {
        id: 19,
        Username: "Hawkeye",
        Gender: "Male",
        School: "S.H.I.E.L.D. Academy",
        Grade: "Graduate",
        Subjects: "Archery",
        Language: "English",
        Schedule: "Tue-Fri, 8:00 AM - 12:00 PM",
        Timezone: "UTC -8",
        Salary: "65 CAD",
        Date: "2024.02.18",
        userId: 19
    },
    {
        id: 20,
        Username: "Robin",
        Gender: "Male",
        School: "Gotham Academy",
        Grade: "Senior",
        Subjects: "Criminology",
        Language: "English",
        Schedule: "Mon-Thu, 10:00 AM - 2:00 PM",
        Timezone: "UTC -5",
        Salary: "75 CAD",
        Date: "2024.02.18",
        userId: 20
    },
    {
        id: 21,
        Username: "Batgirl",
        Gender: "Female",
        School: "Gotham University",
        Grade: "Sophomore",
        Subjects: "Computer Engineering",
        Language: "English",
        Schedule: "Tue-Fri, 11:00 AM - 3:00 PM",
        Timezone: "UTC -6",
        Salary: "60 CAD",
        Date: "2024.02.18",
        userId: 21
    },
    {
        id: 22,
        Username: "Green Arrow",
        Gender: "Male",
        School: "Star City High School",
        Grade: "Freshman",
        Subjects: "Archery",
        Language: "English",
        Schedule: "Mon-Thu, 9:00 AM - 3:00 PM",
        Timezone: "UTC -5",
        Salary: "55 CAD",
        Date: "2024.02.18",
        userId: 22
    },
    {
        id: 23,
        Username: "Supergirl",
        Gender: "Female",
        School: "National City High School",
        Grade: "Junior",
        Subjects: "Kinesiology",
        Language: "English",
        Schedule: "Mon-Wed, 10:00 AM - 2:00 PM",
        Timezone: "UTC -5",
        Salary: "70 CAD",
        Date: "2024.02.18",
        userId: 23
    },
    {
        id: 24,
        Username: "Wonder Woman",
        Gender: "Female",
        School: "Themyscira Academy",
        Grade: "Graduate",
        Subjects: "Law",
        Language: "Greek",
        Schedule: "Tue-Fri, 9:00 AM - 3:00 PM",
        Timezone: "UTC -8",
        Salary: "65 CAD",
        Date: "2024.02.18",
        userId: 24
    },
];

const users = [
    { id: 1, name: "John Doe", email: "john@example.com" },
    { id: 2, name: "Jane Smith", email: "jane@example.com" },
    { id: 3, name: "Alice Johnson", email: "alice@example.com" },
    { id: 4, name: "Bob Williams", email: "bob@example.com" },
    { id: 5, name: "Emma Davis", email: "emma@example.com" },
    { id: 6, name: "Michael Brown", email: "michael@example.com" },
    { id: 7, name: "Jennifer Garcia", email: "jennifer@example.com" },
    { id: 8, name: "William Martinez", email: "william@example.com" },
    { id: 9, name: "Patricia Robinson", email: "patricia@example.com" },
    { id: 10, name: "Matthew Clark", email: "matthew@example.com" },
    { id: 11, name: "Linda Rodriguez", email: "linda@example.com" },
    { id: 12, name: "Christopher Lewis", email: "christopher@example.com" },
    { id: 13, name: "Amanda Lee", email: "amanda@example.com" },
    { id: 14, name: "Jessica Walker", email: "jessica@example.com" },
    { id: 15, name: "Daniel Hall", email: "daniel@example.com" },
    { id: 16, name: "Sarah Young", email: "sarah@example.com" },
    { id: 17, name: "David Allen", email: "david@example.com" },
    { id: 18, name: "Ashley Wright", email: "ashley@example.com" },
    { id: 19, name: "James Lopez", email: "james@example.com" },
    { id: 20, name: "Mary Hill", email: "mary@example.com" },
    { id: 21, name: "Brian Scott", email: "brian@example.com" },
    { id: 22, name: "Karen Green", email: "karen@example.com" },
    { id: 23, name: "Andrew Adams", email: "andrew@example.com" },
    { id: 24, name: "Julie Baker", email: "julie@example.com" }
];

export const getPosts = () => {
    return posts;
}

export const getPost = (id) => {
    return posts.find((post) => post.id === parseInt(id));
}

export const getUser = (userId) => {
    return users.find((user) => user.id === parseInt(userId))
}

